package com.xz.oa.sso.service.unionnet.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-08-22T14:43:54.345+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://SHTH.ESB.ServiceProvider/", name = "ESBProviderServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ESBProviderServiceSoap {

    @WebResult(name = "EprSendLabResult", targetNamespace = "http://SHTH.ESB.ServiceProvider/")
    @RequestWrapper(localName = "EprSendLab", targetNamespace = "http://SHTH.ESB.ServiceProvider/", className = "com.xz.oa.sso.service.unionnet.proxy.EprSendLab")
    @WebMethod(operationName = "EprSendLab", action = "http://SHTH.ESB.ServiceProvider/EprSendLab")
    @ResponseWrapper(localName = "EprSendLabResponse", targetNamespace = "http://SHTH.ESB.ServiceProvider/", className = "com.xz.oa.sso.service.unionnet.proxy.EprSendLabResponse")
    public java.lang.String eprSendLab(
        @WebParam(name = "callType", targetNamespace = "http://SHTH.ESB.ServiceProvider/")
        java.lang.String callType,
        @WebParam(name = "xmlMessage", targetNamespace = "http://SHTH.ESB.ServiceProvider/")
        java.lang.String xmlMessage
    );

    @WebResult(name = "VerifyUserResult", targetNamespace = "http://SHTH.ESB.ServiceProvider/")
    @RequestWrapper(localName = "VerifyUser", targetNamespace = "http://SHTH.ESB.ServiceProvider/", className = "com.xz.oa.sso.service.unionnet.proxy.VerifyUser")
    @WebMethod(operationName = "VerifyUser", action = "http://SHTH.ESB.ServiceProvider/VerifyUser")
    @ResponseWrapper(localName = "VerifyUserResponse", targetNamespace = "http://SHTH.ESB.ServiceProvider/", className = "com.xz.oa.sso.service.unionnet.proxy.VerifyUserResponse")
    public java.lang.String verifyUser(
        @WebParam(name = "strUserCode", targetNamespace = "http://SHTH.ESB.ServiceProvider/")
        java.lang.String strUserCode,
        @WebParam(name = "strUserPwd", targetNamespace = "http://SHTH.ESB.ServiceProvider/")
        java.lang.String strUserPwd
    );
}
